# Generated by Django 3.0.8 on 2020-10-14 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0003_auto_20201013_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='email',
            new_name='Email',
        ),
        migrations.AddField(
            model_name='students',
            name='Address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='Age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='Course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='System.Courses'),
        ),
        migrations.AddField(
            model_name='students',
            name='DOB',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='Guardian_Name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='High_School',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
