# Generated by Django 3.0.8 on 2020-10-15 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0004_auto_20201014_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates',
            name='Barcode',
            field=models.ImageField(blank=True, null=True, upload_to='barcodes'),
        ),
    ]
