# Generated by Django 3.0.8 on 2020-10-15 05:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0005_auto_20201015_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificates',
            name='id',
        ),
        migrations.AddField(
            model_name='certificates',
            name='new_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
