# Generated by Django 3.0.8 on 2020-10-15 05:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0006_auto_20201015_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certificates',
            name='new_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
