# Generated by Django 3.0.8 on 2020-10-15 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0007_auto_20201015_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificates',
            old_name='Cerificate',
            new_name='Certificate',
        ),
    ]
