# Generated by Django 3.0.8 on 2020-10-15 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0008_auto_20201015_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='Course',
        ),
    ]
