# Generated by Django 3.0.8 on 2020-10-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0011_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='Proof',
            field=models.ImageField(null=True, upload_to='requests'),
        ),
    ]
